<?php
/**
 * Say Hello,
 *  __    __  ___   __                  _
 * / / /\ \ \/ _ \ / _\_ __   ___   ___| | __
 * \ \/  \/ / /_)/ \ \| '_ \ / _ \ / __| |/ /
 *  \  /\  / ___/  _\ \ |_) | (_) | (__|   <
 *   \/  \/\/      \__/ .__/ \___/ \___|_|\_\
 *                    |_|
 *
 * WARNING: This file is part of the core WP Spock Framework. DO NOT edit this file under any circumstances.
 *
 */

use WPScotty\WPSpock\Foundation\Theme;

require_once __DIR__ . '/bootstrap/autoload.php';

$GLOBALS[ 'WPSpock' ] = new Theme();