<?php
/**
 * WP Spock.
 *
 * WARNING: This file is part of the core WP Spock Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the resources/views.
 */
spock()->view('main/page.php');